apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-manager
spec:
  selector:
    matchLabels:
      app: customer-manager
  replicas: 1
  template:
    metadata:
      labels:
        app: customer-manager
    spec:
      containers:
        - name: customer-manager
          image: hsbc/customer-manager-service:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/dev
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10

---

apiVersion: v1
kind: Service
metadata:
  name: customer-manager-service
spec:
  selector:
    app: customer-manager
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: customer-manager-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: customer-manager-service
                port:
                  number: 8080
